# Generated by Django 2.1.5 on 2019-01-22 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recently_viewed', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recentlyviewed',
            name='product',
        ),
        migrations.AddField(
            model_name='recentlyviewed',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='recently_viewed', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
