# Generated by Django 2.1.5 on 2019-01-07 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='Number of likes')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Number of view')),
                ('add_to_cart', models.PositiveIntegerField(default=0, verbose_name='Added to cart')),
                ('add_to_wish_list', models.PositiveIntegerField(default=0, verbose_name='Added to wish list')),
                ('purchase', models.PositiveIntegerField(default=0, verbose_name='Purchased')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='catalog.Product')),
            ],
        ),
    ]
