# Generated by Django 2.1.5 on 2019-01-09 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='product',
            name='additional_category',
        ),
        migrations.AddField(
            model_name='product',
            name='additional_category',
            field=models.ManyToManyField(blank=True, null=True, to='catalog.AdditionalCategoryOption', verbose_name='Tags(additional category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.ProductSubcategory', verbose_name='Subcategory'),
        ),
    ]
