# Generated by Django 2.1.5 on 2019-01-09 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20190109_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='additional_category',
            field=models.ManyToManyField(blank=True, to='catalog.AdditionalCategoryOption', verbose_name='Tags(additional category'),
        ),
    ]
