# Generated by Django 2.1.5 on 2019-01-09 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20190109_0854'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productsize',
            options={'verbose_name': 'Размер', 'verbose_name_plural': 'Размеры'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='displayed',
            new_name='display',
        ),
    ]
