# Generated by Django 2.1.5 on 2019-01-09 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20190109_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(related_name='sizes', to='catalog.ProductSize', verbose_name='Размер'),
        ),
    ]
